import type { Sandbox } from "../lib/sandbox";
import {
  getDynamicDbUserId,
  resolveDynamicDbUserRoles,
  DYNAMIC_DB_BASE_URL,
} from "./dynamic-db-config";
import { emptyGeneratedDdbFiles } from "./codegen";

export type EnsureDdbStackOptions = {
  projectId: string;
  userId?: string;
  roles?: string[];
};

function upsertEnvLine(content: string, key: string, value: string): string {
  const line = `${key}=${value}`;
  const keyPattern = new RegExp(`^${key}=.*$`, "m");
  if (keyPattern.test(content)) return content.replace(keyPattern, line);
  if (content.trim().length > 0) return `${content.trimEnd()}\n${line}\n`;
  return `${line}\n`;
}

function buildEnvContent(
  existing: string,
  projectId: string,
  userId: string,
  roles: string[],
): string {
  let content = existing.trim()
    ? existing
    : "# Dynamic DB — 由 Browser ESM Studio 自动写入\n# 导出 ZIP 后请在本机 Vite 配置 /ddb 代理（见 vite.config.ts）\n";
  content = upsertEnvLine(content, "VITE_DDB_PROJECT_ID", projectId);
  content = upsertEnvLine(content, "VITE_DDB_USER_ID", userId);
  content = upsertEnvLine(content, "DDB_USER_ID", userId);
  const rolesValue = roles.join(",");
  content = upsertEnvLine(content, "VITE_DDB_ROLES", rolesValue);
  content = upsertEnvLine(content, "DDB_ROLES", rolesValue);
  return content.endsWith("\n") ? content : `${content}\n`;
}

function bindingTs(projectId: string, userId: string, roles: string[]): string {
  return `// @generated by Browser ESM Studio — do not hand-edit projectId
export const ddbBinding = {
  projectId: ${JSON.stringify(projectId)},
  userId: ${JSON.stringify(userId)},
  roles: ${JSON.stringify(roles)} as string[],
  baseUrl: "/ddb",
} as const;
`;
}

function ddbConfigTs(): string {
  return `/** Dynamic DB 固定 Provider 与浏览器代理前缀 */
export const DDB_API_BASE_URL = ${JSON.stringify(DYNAMIC_DB_BASE_URL)} as const;
export const DDB_DEV_PROXY_PREFIX = "/ddb" as const;
export const DDB_MAX_PAGE_SIZE = 50 as const;
export const DDB_DEFAULT_LIST_PAGE_SIZE = DDB_MAX_PAGE_SIZE;

/** Preview / 导出后本机 Vite：一律走同源 /ddb 代理 */
export function resolveDdbClientBaseUrl(): string {
  return DDB_DEV_PROXY_PREFIX;
}
`;
}

function dbTs(): string {
  return `import {
  createDynamicDbClient,
  type DynamicDbClient,
  DynamicDbError,
  isDynamicDbError,
} from "@qzsy/dynamic-db-client";
import { ddbBinding } from "../config/ddb-binding.ts";
import { resolveDdbClientBaseUrl } from "../config/ddb.ts";
import { createGeneratedDb, type GeneratedDb } from "../ddb/generated/index.ts";

export type AppDb = DynamicDbClient<GeneratedDb> & GeneratedDb;

let cachedDb: AppDb | null = null;
let cachedDbKey = "";

export function isDdbConfigured(): boolean {
  return Boolean(ddbBinding.projectId);
}

/**
 * 类型安全 Dynamic DB 客户端（Prisma 风格 delegate）。
 * Schema 变更后请让 Agent 执行 dynamic-db codegen，或导出后运行 pnpm ddb:codegen。
 */
export function getDb(): AppDb {
  const projectId = ddbBinding.projectId;
  if (!projectId) {
    throw new Error("未配置 Dynamic DB projectId（ddb-binding）");
  }
  const baseUrl = resolveDdbClientBaseUrl();
  const userId = ddbBinding.userId;
  const roles = ddbBinding.roles.length ? [...ddbBinding.roles] : undefined;
  const cacheKey = \`\${baseUrl}|\${projectId}|\${userId}|\${roles?.join(",") ?? ""}\`;
  if (!cachedDb || cachedDbKey !== cacheKey) {
    cachedDb = createDynamicDbClient({
      baseUrl,
      userId,
      projectId,
      roles,
      db: createGeneratedDb,
    });
    cachedDbKey = cacheKey;
  }
  return cachedDb;
}

export { DynamicDbError, isDynamicDbError };
`;
}

function codegenScript(): string {
  return `/**
 * 从 .env 读取 DDB 配置并运行 \`ddb codegen\`（导出 ZIP 后在本机使用）。
 * Preview 内请用 Agent \`dynamic-db\` / operation: codegen。
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DDB_API_BASE_URL = ${JSON.stringify(DYNAMIC_DB_BASE_URL)};
const PAGE_SIZE_PATTERN = /page_size: args\\.pageSize \\?\\? 20/g;
const PAGE_SIZE_REPLACEMENT = "page_size: Math.min(50, args.pageSize ?? 20)";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function parseEnvFile(path) {
  if (!existsSync(path)) return {};
  const out = {};
  for (const line of readFileSync(path, "utf8").split("\\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const fileEnv = parseEnvFile(join(root, ".env"));
const env = { ...process.env, ...fileEnv };
const projectId = env.DDB_PROJECT_ID || env.VITE_DDB_PROJECT_ID;
const userId = env.DDB_USER_ID || env.VITE_DDB_USER_ID || "dev-user";
const roles = env.DDB_ROLES || env.VITE_DDB_ROLES;

if (!projectId) {
  console.error("[ddb:codegen] 请在 .env 中设置 VITE_DDB_PROJECT_ID");
  process.exit(1);
}

const args = [
  "codegen",
  "--base-url",
  DDB_API_BASE_URL,
  "--project-id",
  projectId,
  "--user-id",
  userId,
  "--out",
  "./src/ddb/generated",
];
if (roles) args.push("--roles", roles);

const result = spawnSync("ddb", args, { cwd: root, stdio: "inherit", shell: true });
if ((result.status ?? 1) === 0) {
  const generated = join(root, "src/ddb/generated");
  const patch = (filePath) => {
    if (!existsSync(filePath)) return;
    const content = readFileSync(filePath, "utf8");
    const patched = content.replace(PAGE_SIZE_PATTERN, PAGE_SIZE_REPLACEMENT);
    if (patched !== content) writeFileSync(filePath, patched, "utf8");
  };
  patch(join(generated, "delegates.ts"));
  const kindsDir = join(generated, "kinds");
  if (existsSync(kindsDir)) {
    for (const name of readdirSync(kindsDir)) {
      if (name.endsWith(".delegate.ts")) patch(join(kindsDir, name));
    }
  }
}
process.exit(result.status ?? 1);
`;
}

function docsMd(): string {
  return `# Dynamic DB

本项目已接入 **@qzsy/dynamic-db-client**。在 Browser ESM Studio Preview 中：

1. Agent 用 \`dynamic-db\` 工具 \`setupSchema\` 定义集合
2. 再执行 \`operation: codegen\`（宿主写入 \`src/ddb/generated\`）
3. 业务代码只用 \`getDb()\`：

\`\`\`ts
import { getDb, isDdbConfigured } from "./lib/db.ts";

if (isDdbConfigured()) {
  const db = getDb();
  const { items } = await db.students.findMany({ page: 1, pageSize: 50 });
}
\`\`\`

导出 ZIP 后可在本机运行 \`pnpm ddb:codegen\`（需 \`@qzsy/dynamic-db-cli\`），并保持 Vite \`/ddb\` 代理。

**禁止**手写第二套 HTTP client / curl 探测 Provider。
`;
}

function viteConfigWithDdbProxy(existing: string): string {
  if (existing.includes('"/ddb"') || existing.includes("'/ddb'")) return existing;

  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

const DDB_API_BASE_URL = ${JSON.stringify(DYNAMIC_DB_BASE_URL)};

export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      "/ddb": {
        target: DDB_API_BASE_URL,
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\\/ddb/, ""),
      },
    },
  },
});
`;
}

function addFileIfMissing(sandbox: Sandbox, path: string, content: string, copied: string[]) {
  if (sandbox.exists(path)) return;
  try {
    sandbox.add(path, content);
    copied.push(path);
  } catch {
    sandbox.write(path, content);
    copied.push(path);
  }
}

function writeAlways(sandbox: Sandbox, path: string, content: string, written: string[]) {
  if (sandbox.exists(path)) {
    sandbox.write(path, content);
  } else {
    sandbox.add(path, content);
  }
  written.push(path);
}

/** 补齐虚拟项目 Dynamic DB 栈：缺啥补啥；binding/.env 始终对齐当前租户 */
export function ensureDdbStack(
  sandbox: Sandbox,
  options: EnsureDdbStackOptions,
): { packageJsonPatched: boolean; filesCopied: string[]; filesUpdated: string[] } {
  const projectId = options.projectId.trim();
  const userId = options.userId?.trim() || getDynamicDbUserId();
  const roles = resolveDynamicDbUserRoles(options.roles);
  const filesCopied: string[] = [];
  const filesUpdated: string[] = [];

  let packageJsonPatched = false;
  if (sandbox.exists("package.json")) {
    try {
      const pkg = JSON.parse(sandbox.read("package.json")) as {
        scripts?: Record<string, string>;
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
      };
      let changed = false;
      pkg.scripts ??= {};
      if (!pkg.scripts["ddb:codegen"]) {
        pkg.scripts["ddb:codegen"] = "node scripts/ddb-codegen.mjs";
        changed = true;
      }
      pkg.dependencies ??= {};
      if (!pkg.dependencies["@qzsy/dynamic-db-client"]) {
        pkg.dependencies["@qzsy/dynamic-db-client"] = "^0.1.1";
        changed = true;
      }
      pkg.devDependencies ??= {};
      if (!pkg.devDependencies["@qzsy/dynamic-db-cli"]) {
        pkg.devDependencies["@qzsy/dynamic-db-cli"] = "^0.1.2";
        changed = true;
      }
      if (changed) {
        sandbox.write("package.json", `${JSON.stringify(pkg, null, 2)}\n`);
        packageJsonPatched = true;
      }
    } catch {
      /* ignore invalid package.json */
    }
  }

  const envExisting = sandbox.exists(".env") ? sandbox.read(".env") : "";
  writeAlways(sandbox, ".env", buildEnvContent(envExisting, projectId, userId, roles), filesUpdated);
  writeAlways(sandbox, "src/config/ddb-binding.ts", bindingTs(projectId, userId, roles), filesUpdated);

  addFileIfMissing(sandbox, "src/config/ddb.ts", ddbConfigTs(), filesCopied);
  addFileIfMissing(sandbox, "src/lib/db.ts", dbTs(), filesCopied);
  addFileIfMissing(sandbox, "scripts/ddb-codegen.mjs", codegenScript(), filesCopied);
  addFileIfMissing(sandbox, "docs/DYNAMIC-DB.md", docsMd(), filesCopied);

  if (sandbox.exists("vite.config.ts")) {
    const next = viteConfigWithDdbProxy(sandbox.read("vite.config.ts"));
    if (next !== sandbox.read("vite.config.ts")) {
      sandbox.write("vite.config.ts", next);
      filesUpdated.push("vite.config.ts");
    }
  } else {
    addFileIfMissing(sandbox, "vite.config.ts", viteConfigWithDdbProxy(""), filesCopied);
  }

  if (!sandbox.exists("src/ddb/generated/index.ts")) {
    const generated = emptyGeneratedDdbFiles();
    for (const [path, content] of Object.entries(generated)) {
      addFileIfMissing(sandbox, path, content, filesCopied);
    }
  }

  return { packageJsonPatched, filesCopied, filesUpdated };
}
